repos:
    - repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1  
      hooks:
        - id: pydocstyle
          args: 
            - --convention=google
    - repo: https://github.com/terrencepreilly/darglint
      rev: v1.8.0
      hooks:
      - id: darglint
default_language_version:
    python: python3.8
